### ISSUE TITLE
Howto build without uploading in anaconda?

### ISSUE THREAD

**Issue by pradal** [openalea/action-build-publish-anaconda#1]
I would like to build and test my package.
Then, on a new tag, upload it in anaconda.

Is it possible?

**Comment by thomasarsouze** [comment]
I think it depends on the level of abstraction we want to use. We can either:
- create a .github/workflow/xxx.yml that manages the different cases of workflow triggering (e.g. build and test on push on master, build (and test) and publish if tagged for publishing). We'd need to create another action, but it'd remain simple and dedicated to one thing.
- modify this action to trigger different scripts according to the tag passed as input. Less "readable" from with the package itself but easier to use

At this point, I have no prefered choice. I might also depend if we want this build / test / deploy strategy to be the same for all packages (i.e. re-write a different xxx.yml for each package or simply change a tag).

**Comment by pradal** [comment]
I like the KISS strategy (the first one).
I think if it is simple it is easier to maintain

**Comment by thomasarsouze** [comment]
This issue has been solved in v0.1.3 and later. A 'publish' input has been added.
