### ISSUE TITLE
Failure when trying to install mamba with version *

### ISSUE THREAD

**Issue by pradal** [openalea/action-build-publish-anaconda#7]
See https://github.com/conda-incubator/setup-miniconda/issues/274

Also all the CI with or without mamba fail (because they tr to install it)

**Comment by thomasarsouze** [comment]
Bugfix found and tested successfully on [openalea/core](https://github.com/openalea/core/actions/runs/3966552986) and [hydroshoot](https://github.com/openalea/hydroshoot/actions/runs/3966806105). Please switch to openalea/action-build-publish-anaconda@v0.1.4 in your CI/CD workflow.
